name: ReleaseFirefox

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*.*

jobs:
  Firefox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rename Manifest
      run: mv manifest-ff.json manifest.json
    - name: Pack extension
      uses: TheDoctor0/zip-release@0.6.2
      with:
        type: 'zip'
        filename: release.zip
        exclusions: '*.git* .github/* *.md manifest-ff.json'
    - name: Publish to Firefox
      uses: wdzeng/firefox-addon@v1
      with:
        addon-guid: ${{ secrets.FIREFOX_EXT_UUID }}
        xpi-path: release.zip
        jwt-issuer: ${{ secrets.FIREFOX_CLIENT_ID }}
        jwt-secret: ${{ secrets.FIREFOX_CLIENT_SECRET }}
